$primary = rgb(6fa791)
$surface = rgb(152326)
$secondary = rgb(79c2b6)
$error = rgb(d2696c)
$tertiary = rgb(dbd0c6)
$surface_lowest = rgb(162528)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
